flowchart TD
    examples_api_response["examples.api_response<br/>1 funcs"]
    examples_colored_logging["examples.colored_logging<br/>1 funcs"]
    examples_config_viewer["examples.config_viewer<br/>6 funcs"]
    examples_custom_renderer["examples.custom_renderer<br/>1 funcs"]
    examples_logger_usage["examples.logger_usage<br/>8 funcs"]
    examples_phase1_features["examples.phase1_features<br/>7 funcs"]
    examples_phase3_progress["examples.phase3_progress<br/>6 funcs"]
    examples_phase4_themes["examples.phase4_themes<br/>7 funcs"]
    examples_phase5_devtools["examples.phase5_devtools<br/>7 funcs"]
    examples_simple_cli["examples.simple_cli<br/>5 funcs"]
    scripts_bump_version["scripts.bump_version<br/>1 funcs"]
    src_clickmd["src.clickmd<br/>158 funcs"]
    examples_phase1_features ==>|29| src_clickmd
    examples_phase5_devtools ==>|19| src_clickmd
    examples_custom_renderer ==>|17| src_clickmd
    examples_phase3_progress ==>|16| src_clickmd
    examples_phase4_themes ==>|15| src_clickmd
    examples_config_viewer ==>|10| src_clickmd
    examples_logger_usage ==>|9| src_clickmd
    scripts_bump_version ==>|6| src_clickmd
    examples_simple_cli -->|2| src_clickmd
    examples_api_response -->|1| src_clickmd
    examples_colored_logging -->|1| src_clickmd
