flowchart TD
    examples__api_response["examples.api_response<br/>1 funcs"]
    examples__colored_logging["examples.colored_logging<br/>1 funcs"]
    examples__config_viewer["examples.config_viewer<br/>6 funcs"]
    examples__custom_renderer["examples.custom_renderer<br/>1 funcs"]
    examples__logger_usage["examples.logger_usage<br/>8 funcs"]
    examples__phase1_features["examples.phase1_features<br/>7 funcs"]
    examples__phase3_progress["examples.phase3_progress<br/>6 funcs"]
    examples__phase4_themes["examples.phase4_themes<br/>7 funcs"]
    examples__phase5_devtools["examples.phase5_devtools<br/>7 funcs"]
    examples__simple_cli["examples.simple_cli<br/>5 funcs"]
    scripts__bump_version["scripts.bump_version<br/>1 funcs"]
    src__clickmd["src.clickmd<br/>158 funcs"]
    examples__phase1_features ==>|29| src__clickmd
    examples__phase5_devtools ==>|19| src__clickmd
    examples__custom_renderer ==>|17| src__clickmd
    examples__phase3_progress ==>|16| src__clickmd
    examples__phase4_themes ==>|15| src__clickmd
    examples__config_viewer ==>|10| src__clickmd
    examples__logger_usage ==>|9| src__clickmd
    scripts__bump_version ==>|6| src__clickmd
    examples__simple_cli -->|2| src__clickmd
    examples__colored_logging -->|1| src__clickmd
    examples__api_response -->|1| src__clickmd
